name: "Install Poetry Action"
author: "step-security"
description: "Installs and configures Poetry"
branding:
  icon: "package"
  color: "green"
inputs:
  version:
    description: "The Poetry version to install"
    required: true
    default: "latest"
  virtualenvs-create:
    description: "Whether Poetry should create a virtualenv or not"
    required: false
    default: "true"
  virtualenvs-in-project:
    description: "Whether Poetry should create virtualenvs in the project directory or not"
    required: false
    default: "false"
  virtualenvs-path:
    description: "The Poetry virtualenv path"
    required: false
    default: "{cache-dir}/virtualenvs"
  installer-parallel:
    description: "Whether to install many packages at once or one by one. This can fix PyPI DNS resolution errors, but also slows down the installation"
    required: false
    default: "true"
  installation-arguments:
    description: "Arguments passed directly to the Poetry installation script. For example --force."
    required: false
  plugins:
    description: "Whitespace-delimited list of poetry plugins to install. Requires Poetry>=1.2"
    required: false
runs:
  using: "composite"
  steps:
    - name: Check subscription
      shell: bash
      run: |
        # validate subscription status
        API_URL="https://agent.api.stepsecurity.io/v1/github/$GITHUB_REPOSITORY/actions/subscription"

        # Set a timeout for the curl command (3 seconds)
        RESPONSE=$(curl --max-time 3 -s -w "%{http_code}" "$API_URL" -o /dev/null) || true
        CURL_EXIT_CODE=$?

        # Decide based on curl exit code and HTTP status
        if [ $CURL_EXIT_CODE -ne 0 ]; then
          echo "Timeout or API not reachable. Continuing to next step."
        elif [ "$RESPONSE" = "200" ]; then
          :
        elif [ "$RESPONSE" = "403" ]; then
          echo "Subscription is not valid. Reach out to support@stepsecurity.io"
          exit 1
        else
          echo "Timeout or API not reachable. Continuing to next step."
        fi

    - name: Install and configure Poetry
      run: $GITHUB_ACTION_PATH/main.sh
      shell: bash
      env:
        VERSION:                ${{ inputs.version }}
        VIRTUALENVS_CREATE:     ${{ inputs.virtualenvs-create }}
        VIRTUALENVS_IN_PROJECT: ${{ inputs.virtualenvs-in-project }}
        VIRTUALENVS_PATH:       ${{ inputs.virtualenvs-path }}
        INSTALLER_PARALLEL:     ${{ inputs.installer-parallel }}
        INSTALLATION_ARGUMENTS: ${{ inputs.installation-arguments }}
        POETRY_PLUGINS:         ${{ inputs.plugins }}
